runtime: python37  # 根据你的 Python 版本修改

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  min_pending_latency: automatic
  max_pending_latency: automatic

entrypoint: gunicorn -b :$PORT RestaurantOrderSystem.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "RestaurantOrderSystem.settings"

runtime_config:
  python_version: 3

beta_settings:
    cloud_sql_instances: simaker:australia-southeast2:restaurantordersystem-version-1-1-0
