# Generated by Django 4.2 on 2023-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_contents',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='unfinished', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_id',
            field=models.PositiveIntegerField(),
        ),
    ]
