# Generated by Django 4.2 on 2023-05-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_is_prepared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_completed',
            new_name='is_checkout',
        ),
    ]
