# Generated by Django 4.2 on 2023-05-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
