# Generated by Django 4.2.1 on 2023-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_customer_id_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ID',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
