# Generated by Django 4.2.1 on 2023-05-11 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_products_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ID',
        ),
        migrations.AlterField(
            model_name='products',
            name='ProductsID',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
