# Generated by Django 4.2 on 2023-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_order_cart_contents_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_prepared',
            field=models.BooleanField(default=False),
        ),
    ]
