# Generated by Django 4.2.1 on 2023-05-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_is_remainder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_remainder',
            new_name='is_reminder',
        ),
    ]
