# Generated by Django 4.2.1 on 2023-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_products_id_alter_products_productsid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_name', models.CharField(max_length=255)),
                ('flavor_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='flavors',
            field=models.JSONField(default=list),
        ),
    ]
