# Generated by Django 4.2.1 on 2023-05-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paralysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paralysis_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Spicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spicy_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.AddField(
            model_name='products',
            name='paralysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.paralysis'),
        ),
        migrations.AddField(
            model_name='products',
            name='spicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.spicy'),
        ),
    ]
