# Generated by Django 4.2.1 on 2023-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_paralysis_spicy_delete_flavor_products_paralysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paralysis',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spicy',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
