# Generated by Django 4.2.1 on 2023-05-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_paralysis_id_alter_spicy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flavors',
        ),
    ]
