# Generated by Django 4.2.1 on 2023-05-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_order_flavors'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='descreption',
            field=models.CharField(default='', max_length=128),
        ),
    ]
