# Generated by Django 4.2.1 on 2023-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_products_descreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='SecondaryName',
            field=models.CharField(default='', max_length=128),
        ),
    ]
