# Generated by Django 4.2.1 on 2023-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_products_secondaryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='descreption',
            field=models.CharField(default='', max_length=256),
        ),
    ]
