# Generated by Django 4.2 on 2023-05-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descreption',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
